### PR TITLE
Link sdb and spp libs wholly to rz_util

### PR DESCRIPTION
**Pull request by p371jah**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Requires https://github.com/rizinorg/sdb/pull/25

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
OpenBSD:
```
librz/util/meson.build:88:0: ERROR: Unknown method "as_link_whole" in object.
```

**Comment by p371jah** [comment]
`as_link_whole` was introduced in meson 0.56....

**Comment by p371jah** [comment]
Well if it isn't allowed to change minimal required meson version, we can just add new dependency with `link_whole` to `sdb` project.

**Comment by XVilka** [comment]
No, I think it's fine to use newer meson, we just could install it from `pip`.

**Comment by XVilka** [comment]
@pelijah could you please just revert back to `as_link_whole` but add `pip install meson` to OpenBSD? I think this is a better way. cc @ret2libc @thestr4ng3r 
Eventually OpenBSD will update their meson version too.

**Comment by p371jah** [comment]
> @pelijah could you please just revert back to `as_link_whole` but add `pip install meson` to OpenBSD?

For `spp_dep`? I think it would be better to use `link_whole` directly since `spp_dep` is declared in main `meson.build` file.

**Comment by XVilka** [comment]
Ok, no problem then. I thought it's about SDB.

**Comment by XVilka** [comment]
By the way, seems OpenBSD ports have updated Meson already: https://openports.se/devel/meson

**Comment by ret2libc** [comment]
Ok fix the `WARNING: Project targeting '>=0.50.0' but tried to use feature introduced in '0.56.0': dep.as_link_whole.` please.

**Comment by ret2libc** [comment]
Got this while compiling on my system:
```
/usr/bin/ld: librz/core/librz_core.so.0.2.0-git.p/cmd.c.o: in function `is_tcache_32':
/home/rschiron/projects/rizinorg/rizin/build-sdb-whole/../librz/core/linux_heap_glibc.c:130: undefined reference to `round'
```
I have no idea how it relates to your PR though...

**Comment by p371jah** [comment]
> Ok fix the `WARNING: Project targeting '>=0.50.0' but tried to use feature introduced in '0.56.0': dep.as_link_whole.` please.

Requires to update minimal meson version in `sdb` too.

**Comment by ret2libc** [comment]
> > Ok fix the `WARNING: Project targeting '>=0.50.0' but tried to use feature introduced in '0.56.0': dep.as_link_whole.` please.
> 
> Requires to update minimal meson version in `sdb` too.

If we do it for rizin it should be no problem doing it for sdb as well.

However we should be aware that if we update too much the min required meson version we risk that some distros won't be able to easily package rizin in their distros.

**Comment by p371jah** [comment]
> However we should be aware that if we update too much the min required meson version we risk that some distros won't be able to easily package rizin in their distros.

Thats why I have proposed a workaround

**Comment by ret2libc** [comment]
> > However we should be aware that if we update too much the min required meson version we risk that some distros won't be able to easily package rizin in their distros.
> 
> Thats why I have proposed a workaround

I agree with you. In my opinion we should wait a little bit to update the min required version to 0.56.0 . Ubuntu 20.10, for example, seems to still use 0.55.3, so it would be a problem there.

**Comment by karliss** [comment]
Another issue with meson version increase is that 0.56 raises minimum python version from 3.5 to 3.6. And 3.5 is the version available on Ubuntu 16.04. So you can't even install it using pip unless you also install a newer python.

**Comment by XVilka** [comment]
It's always possible to build Python 3.6 from sources, even on something old like Debian Wheezy: https://github.com/rizinorg/rizin/runs/2247159748#step:6:1

**Comment by ret2libc** [comment]
> It's always possible to build Python 3.6 from sources, even on something old like Debian Wheezy: https://github.com/rizinorg/rizin/runs/2247159748#step:6:1

Yes but that's not something distros are going to do for sure. Packagers have to use the system provided python/meson to build packages usually, so it's better to use a workaround for link_whole IMO.

**Comment by karliss** [comment]
My previous comment might be wrong, looking at the meson repo  and Cutter CI one more time indicates that 0.56.0 might be still compatible with python 3.5.  Cutter CI contains
```
 # 0.56.1 doesn't work with python 3.5 on Ubuntu 16.04
pip install meson==0.56.0
```
Looking at the commits it might be that 0.56.1 broke the compatibility and then there are commits in 0.56.2 removing some usage of python 3.6 features.   Of course I don't mind against ability to compile on 20.04 using system meson.

**Comment by p371jah** [comment]
Requires https://github.com/rizinorg/sdb/pull/26

**Comment by p371jah** [comment]
> 
> 
> Got this while compiling on my system:
> 
> ```
> /usr/bin/ld: librz/core/librz_core.so.0.2.0-git.p/cmd.c.o: in function `is_tcache_32':
> /home/rschiron/projects/rizinorg/rizin/build-sdb-whole/../librz/core/linux_heap_glibc.c:130: undefined reference to `round'
> ```
> 
> I have no idea how it relates to your PR though...

@ret2libc Please try again to verify my fix

**Review by ret2libc — APPROVED** [review]

**Comment by XVilka** [comment]
I merged https://github.com/rizinorg/sdb/pull/25. Please update this PR with the new SDB commit.

**Review by XVilka — APPROVED** [review]
